# General settings
debug: false
AUGMENT: false
VALIDATION_FRAC: 0.4
AUGMENTATION_FRACTION: 0.05
EPOCHS: 50
SKIP_ASSERT : false

# Checkpointing
checkpoint_dir: "/eng/home/koushani/Documents/Multimodal_XAI/Brain-Pattern-Identification-using-Multimodal-Classification/root/checkpoints"
log_directory: "/eng/home/koushani/Documents/Multimodal_XAI/Brain-Pattern-Identification-using-Multimodal-Classification/root/"
save_dir: "/eng/home/koushani/Documents/Multimodal_XAI/Brain-Pattern-Identification-using-Multimodal-Classification/root/plots/"
last_optimizer: null
last_regularization_lambda: null
checkpointing_enabled: true

# Paths (new references)
root_dir: "/data2/users/koushani/HMS_data"
train_eegs: "${root_dir}/train_eegs/"
train_spectr: "${root_dir}/train_spectr/"
test_eegs: "${root_dir}/test_eegs/"
test_spectr: "${root_dir}/test_spectr/"

# System settings
seed: 42
gpu_idx: 0
device: "cuda"

# EEG settings
EEG_COLUMNS:
  - Fp1
  - F3
  - C3
  - P3
  - F7
  - T3
  - T5
  - O1
  - Fz
  - Cz
  - Pz
  - Fp2
  - F4
  - C4
  - P4
  - F8
  - T4
  - T6
  - O2
  - EKG

eeg_features: &eeg_features  # Anchor for EEG features
  - Fp1
  - F3
  - C3
  - P3
  - F7
  - T3
  - T5
  - O1
  - Fz
  - Cz
  - Pz
  - Fp2
  - F4
  - C4
  - P4
  - F8
  - T4
  - T6
  - O2

# Label mappings
classes:
  - Seizure
  - LPD
  - GPD
  - LRDA
  - GRDA
  - Other
label2name: {0: "Seizure", 1: "LPD", 2: "GPD", 3: "LRDA", 4: "GRDA", 5: "Other"}
name2label: {"Seizure": 0, "LPD": 1, "GPD": 2, "LRDA": 3, "GRDA": 4, "Other": 5}
n_classes: 6

# Spectrogram settings
SPECTR_COLUMNS:
  - time
  - LL_0.59
  - LL_0.78
  - LL_0.98
  - LL_1.17
  - LL_1.37
  - LL_1.56
  - LL_1.76
  - LL_1.95
  - LL_2.15
  - LL_2.34
  - LL_2.54
  - LL_2.73
  - LL_2.93
  - LL_3.13
  - LL_3.32
  - LL_3.52
  - LL_3.71
  - LL_3.91
  - LL_4.1
  - LL_4.3
  - LL_4.49
  - LL_4.69
  - LL_4.88
  - LL_5.08
  - LL_5.27
  - LL_5.47
  - LL_5.66
  - LL_5.86
  - LL_6.05
  - LL_6.25
  - LL_6.45
  - LL_6.64
  - LL_6.84
  - LL_7.03
  - LL_7.23
  - LL_7.42
  - LL_7.62
  - LL_7.81
  - LL_8.01
  - LL_8.2
  - LL_8.4
  - LL_8.59
  - LL_8.79
  - LL_8.98
  - LL_9.18
  - LL_9.38
  - LL_9.57
  - LL_9.77
  - LL_9.96
  - LL_10.16
  - LL_10.35
  - LL_10.55
  - LL_10.74
  - LL_10.94
  - LL_11.13
  - LL_11.33
  - LL_11.52
  - LL_11.72
  - LL_11.91
  - LL_12.11
  - LL_12.3
  - LL_12.5
  - LL_12.7
  - LL_12.89
  - LL_13.09
  - LL_13.28
  - LL_13.48
  - LL_13.67
  - LL_13.87
  - LL_14.06
  - LL_14.26
  - LL_14.45
  - LL_14.65
  - LL_14.84
  - LL_15.04
  - LL_15.23
  - LL_15.43
  - LL_15.63
  - LL_15.82
  - LL_16.02
  - LL_16.21
  - LL_16.41
  - LL_16.6
  - LL_16.8
  - LL_16.99
  - LL_17.19
  - LL_17.38
  - LL_17.58
  - LL_17.77
  - LL_17.97
  - LL_18.16
  - LL_18.36
  - LL_18.55
  - LL_18.75
  - LL_18.95
  - LL_19.14
  - LL_19.34
  - LL_19.53
  - LL_19.73
  - LL_19.92

RL: *eeg_features  # RL references the same list as LL

LP: &lp_anchor  # LP list is anchored with the name 'lp_anchor'
  - Fp2
  - F4
  - C4
  - P4
  - F8
  - T4
  - T6
  - O2

RP: *lp_anchor  # RP references the same list as LP

n_folds: 5

# Dataset Preprocessing
bandpass_filter:
  low: 0.5
  high: 20
  order: 2

rand_filter:
  probab: 0.1
  low: 10
  high: 20
  band: 1.0
  order: 2

freq_channels:
  - [0.5, 4.5]

filter_order: 2
random_close_zone: 0.0  # Example: 0.2

# Feature Mapping
map_features:
  - [Fp1, F7]
  - [F7, T3]
  - [T3, T5]
  - [T5, O1]
  - [Fp1, F3]
  - [F3, C3]
  - [C3, P3]
  - [P3, O1]
  - [Fp2, F8]
  - [F8, T4]
  - [T4, T6]
  - [T6, O2]
  - [Fp2, F4]
  - [F4, C4]
  - [C4, P4]
  - [P4, O2]
  - [Fz, Cz]
  - [Cz, Pz]


simple_features:
  - Fz
  - Cz
  - Pz
  - EKG

# Input/output settings
n_map_features: 18
in_channels: 19

seq_length: 50  # seconds
sampling_rate: 200  # Hz
nsamples: 10000  # seq_length * sampling_rate
out_samples: 2000  # nsamples // 5

debug_input_size: 4096
in_chans: 1

batch_size: 256
num_workers: 50
fixed_length: 3000
image_size: [400, 300]